server:
  port: 8085

spring:
  data:
    redis:
      host: 192.168.10.58
      port: 6379

  jpa:
    generate-ddl: true
    open-in-view: false

  datasource:
    url: jdbc:postgresql://workserver:5432/book_db
    username: postgres
    password: postgres
    hikari:
      schema: book_schema
      connection-timeout: 10000
